// Generated by gencpp from file random_num_addition/random.msg
// DO NOT EDIT!


#ifndef RANDOM_NUM_ADDITION_MESSAGE_RANDOM_H
#define RANDOM_NUM_ADDITION_MESSAGE_RANDOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace random_num_addition
{
template <class ContainerAllocator>
struct random_
{
  typedef random_<ContainerAllocator> Type;

  random_()
    : x(0)
    , y(0)  {
    }
  random_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::random_num_addition::random_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::random_num_addition::random_<ContainerAllocator> const> ConstPtr;

}; // struct random_

typedef ::random_num_addition::random_<std::allocator<void> > random;

typedef boost::shared_ptr< ::random_num_addition::random > randomPtr;
typedef boost::shared_ptr< ::random_num_addition::random const> randomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::random_num_addition::random_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::random_num_addition::random_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace random_num_addition

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'random_num_addition': ['/home/nidhi/catkin_ws/src/random_num_addition/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::random_num_addition::random_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::random_num_addition::random_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::random_num_addition::random_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::random_num_addition::random_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::random_num_addition::random_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::random_num_addition::random_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::random_num_addition::random_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd7b43fd41d4c47bf5c703cc7d016709";
  }

  static const char* value(const ::random_num_addition::random_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd7b43fd41d4c47bULL;
  static const uint64_t static_value2 = 0xf5c703cc7d016709ULL;
};

template<class ContainerAllocator>
struct DataType< ::random_num_addition::random_<ContainerAllocator> >
{
  static const char* value()
  {
    return "random_num_addition/random";
  }

  static const char* value(const ::random_num_addition::random_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::random_num_addition::random_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n\
int32 y\n\
";
  }

  static const char* value(const ::random_num_addition::random_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::random_num_addition::random_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct random_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::random_num_addition::random_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::random_num_addition::random_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RANDOM_NUM_ADDITION_MESSAGE_RANDOM_H
